version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    volumes:
      - ./backend/.env:/app/.env
      - upload-volume:/app/upload

  postgres:
    image: postgres:latest
    env_file:
      - ./backend/.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - 5435:5432
    expose:
      - "5435"

  frontend:
    build:
      context: ./frontend-et
      dockerfile: Dockerfile
    ports:
      - "4200:4200"

  ai-logic-et:
    build:
      context: ./ai-logic-et
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./ai-logic-et:/app
      - image-volume:/app/Images

volumes:
  database-data:
  upload-volume:
  image-volume:
